version: '3.8'

services:
  task-api:
    tty: true
    container_name: task-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TaskManagement_Db=Server=sqlserver;Database=TaskManagement_DEV;User ID=sa;Password=123456@abc;Encrypt=False
      - ConnectionStrings__Redis=redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  sqlserver:
      build:
        context: .
        dockerfile: Dockerfile.sqlserver
      container_name: sqlserver
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: "123456@abc"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
      volumes:
      - ./init-db.sh:/init-db.sh
      - ./Script.sql:/Script.sql
      command: ["/bin/bash", "/init-db.sh"]