name: Deploy to Multiple Environments
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} .
      - name: Push to Registry
        run: docker push myapp:${{ github.sha }}
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: |
          # Triển khai tới môi trường Dev
          kubectl apply -f k8s/dev/ --context=dev-cluster
  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: |
          # Triển khai tới Staging
          kubectl apply -f k8s/staging/ --context=staging-cluster
  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          # Triển khai tới Production (có thể thêm bước phê duyệt thủ công)
          kubectl apply -f k8s/prod/ --context=prod-cluster
